## Logical service name with which it registers itself at the service registry
spring:
  application:
    name: account-service
  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:~/test
      username: sa
      password:
      h2:
        console:
          enabled: true
  jpa:
      hibernate.ddl-auto: update
      generate-ddl: false
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
## Port on which this microservice is going to run
server:
  port: 6060

## Where to find the service registry
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true